### ISSUE TITLE
Annoying bugs on v1.5.3.2

### ISSUE THREAD

**Issue by u0xaa55** [syuchan1005/GitPrefix#11]
On OSX and with Webstorm 2018.2:

-1. [Critical bug, Non blocking, No raised exception] creating a new project, creating a .gitprefix file, adding ":bug: Bugfix" into it, closing it and reopening the same file led me to an infinite loading message:
<img width="461" alt="capture d ecran 2018-07-31 a 22 44 27" src="https://user-images.githubusercontent.com/15631355/43486774-f5a20434-9514-11e8-8444-ee20c28c4028.png">
Even new file edition now shows the loading message,
<img width="388" alt="capture d ecran 2018-07-31 a 23 20 09" src="https://user-images.githubusercontent.com/15631355/43487971-879d7c6c-9518-11e8-86ae-1050f8741c08.png">
Can't edit any file while having this message,
Closing and reopening the files do not solve the problem, 
I had to restart Webstorm to get rid of the loading message on both .gitprefix and test files.

-2. [Annoying bug, Known bug, Non blocking, No raised exception] after adding an entry (":bug: Bugfix"), I tried to add ":sparkles: Feature" but I just could type ":s" and then the cursor won't write anything more. I had to remove the line + some chars of the first line, retype them, try "sss" on a new line (without the ":"), it worked, remove the "sss" and tried ":sparkles: Feature" to have it to work!

-3. [Minor bug, Non blocking bug, No raised exception][Maybe by design?] Into .gitprefix I don't have the corresponding emoji next to the line number (even after manually save the .gitprefix file) until I open the commit window or after reopening the .gitprefix file.
Before opening commit window:
<img width="283" alt="capture d ecran 2018-07-31 a 23 07 31" src="https://user-images.githubusercontent.com/15631355/43487371-b3cc42ca-9516-11e8-9946-45f390e0be27.png">
When and after opening commit window:
<img width="461" alt="capture d ecran 2018-07-31 a 23 09 35" src="https://user-images.githubusercontent.com/15631355/43488515-59279aa0-951a-11e8-900f-a16775f8df6b.png">

**Comment by syuchan1005** [comment]
All these bugs are known to have problems with parsing. I want something, but it is very difficult.
I would like to fix it in the next minor release.
