### ISSUE TITLE
hope can suppoort set .gitprefix file path

### ISSUE THREAD

**Issue by bluelovers** [syuchan1005/GitPrefix#13]
like this
![2018-08-10-12-49-21-5](https://user-images.githubusercontent.com/167966/43939353-12f7ea10-9c9c-11e8-8a9b-b9e86bd5e684.png)

make it without put on project root

**Comment by syuchan1005** [comment]
Please wait for version 1.5.4.3

**Comment by bluelovers** [comment]
so fast lol thx

--------

btw, i make a plugin, not sure do u need or not
https://github.com/bluelovers/idea-cjk-conv
