### ISSUE TITLE
Out of memery on try to commit 1 line with Pycharm 

### ISSUE THREAD

**Issue by pymen** [syuchan1005/GitPrefix#15]
![image](https://user-images.githubusercontent.com/2733052/45442174-f632b480-b6c9-11e8-997b-163ba2044d42.png)

PyCharm 2018.3 EAP (Professional Edition)
Build #PY-183.2407.3, built on September 11, 2018
PyCharm EAP User
Expiration date: October 11, 2018
JRE: 1.8.0_152-release-1226-b7 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.12.3-041203-generic

**Comment by pymen** [comment]
on last version and on several previous

**Comment by pymen** [comment]
!! even of fresh pycharm installation with only 1 current plugin

**Comment by syuchan1005** [comment]
@pymen 
Could you give me your .gitprefix file?

**Comment by pymen** [comment]
:bug:     BugFix
:lock:    SecurityFix # Comment
:recycle: Refactoring
:books:   Documentation

**Comment by pymen** [comment]
```
:bug:     BugFix
:lock:    SecurityFix # Comment
:recycle: Refactoring
:books:   Documentation
```

**Comment by pymen** [comment]
![image](https://user-images.githubusercontent.com/2733052/45447893-a22fcc00-b6d9-11e8-9161-10fd59914c66.png)

**Comment by pymen** [comment]
1) maybe last blank line breaks everything.. 
2) The same behaviour was on Pycharm 2018.1

**Comment by syuchan1005** [comment]
Did the bug fix?

**Comment by pymen** [comment]
yes, now it works perfectly!!
![image](https://user-images.githubusercontent.com/2733052/45943957-1aa75e80-bff1-11e8-9268-d08b05d90a93.png)

**Comment by syuchan1005** [comment]
good!
