### ISSUE TITLE
Not working on PhpStorm

### ISSUE THREAD

**Issue by aglipanci** [syuchan1005/GitPrefix#17]
PhpStorm 2018.2.3 (using Material UI theme)
Build #PS-182.4323.68, built on September 13, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

Version 2.0 does not work at all, there are no Emoji shown on the .gitprefix screen

![image](https://user-images.githubusercontent.com/2675283/48281214-2e4e3d80-e456-11e8-8f9c-d4524d905d2f.png)

Also, nothing is shown on the commit window:
![image](https://user-images.githubusercontent.com/2675283/48281280-605f9f80-e456-11e8-804b-e023786efa65.png)

I did a manual install of version 1.5 and I was able to see the prefix window, but the only option for selection was No Prefix and the values from .gitprefix were not taken into consideration at all.

Let me know if I should provide any additional information.

**Comment by syuchan1005** [comment]
File Type is not setting to GitPrefix file.
Please change File Type from Preference.

**Comment by aglipanci** [comment]
Hey @syuchan1005,
Thanks for the reply!

I actually have created the file as GitPrefix file type and that's also defined on the File Types here:
![image](https://user-images.githubusercontent.com/2675283/48300932-01496b80-e4e6-11e8-97a4-f6449ee93800.png)

However it seems like it's getting overridden by Git file types (which by the way are not present on this list)

Any other idea what I can try?

**Comment by syuchan1005** [comment]
You can look for FileType while looking at file icon.

**Comment by aglipanci** [comment]
Yes, that's what I was trying to say that the .gitprefix file it's not a GitPrefix file type but a GIT file type and it seems that I cannot do anything to change that.

Do you have any suggestion ?

**Comment by syuchan1005** [comment]
Try deleting or excluding .gitprefix from the GIT file type

**Comment by aglipanci** [comment]
Already tried but I can't seem to be able to do that. There is not Git file type on the list.

**Comment by syuchan1005** [comment]
Is there the same problem if you change the theme?

**Comment by aglipanci** [comment]
Actually it didn't work.

**Comment by syuchan1005** [comment]
Umm... My PhpStorm(2018.2.5, macOS) work well.
Sorry, I have no idea for the problem.

**Comment by nitwhiz** [comment]
Changing the file type to `.gitprefix` (removing the asterisk) brought GitPrefix back for me.
