### ISSUE TITLE
Hope it can support 2019.2 version

### ISSUE THREAD

**Issue by KenmuHuang** [syuchan1005/GitPrefix#18]
It can work in 2019.1 version, then, can't work in 2019.2 version.
Hope it can support 2019.2 version

**Comment by syuchan1005** [comment]
@KenmuHuang 
Thanks issue. but, I busy now. The response may be delayed. Sorry.

**Comment by syuchan1005** [comment]
GitPrefix v2.1.0 now supports 2019.2. Please wait until the update.
