### ISSUE TITLE
Don't work in Pycharm 2020.1

### ISSUE THREAD

**Issue by gollum23** [syuchan1005/GitPrefix#24]
Don't show emoji selector at commit window

![Screenshot_20200414_133652](https://user-images.githubusercontent.com/1058783/79261147-0639e980-7e55-11ea-8b49-778826d2c33b.png)

**Comment by gollum23** [comment]
Do you need more information?

**Comment by syuchan1005** [comment]
I'm sorry for the delay in replying due to my busy work schedule.

There is a bug, but the UI is now visible.
I'm going to close this issue after fixing the bug.

I think we're going to be late.

**Comment by gollum23** [comment]
Thanks for your work, i love this plugin

**Comment by gollum23** [comment]
The selector now show, but when y select not show text in the commit and selector closes without select option.

**Comment by syuchan1005** [comment]
I'm sorry for the delay in responding.
We have contacted Jetbrains about the bug.
(https://youtrack.jetbrains.com/issue/IDEA-239673)
It may take some time.

P.S. Thanks for saying that you love this plugin!

**Comment by KenmuHuang** [comment]
AppCode 2020.1 also have the same issue, can't replace it with selected item. Please fix it, thanks.
![截屏2020-05-16 10 20 03](https://user-images.githubusercontent.com/11454770/82108108-eb61da00-975e-11ea-9073-f4402e9231a6.png)

**Comment by gollum23** [comment]
https://youtrack.jetbrains.com/issue/IDEA-239673#focus=streamItem-27-4156398.0-0 Here response your question @syuchan1005

**Comment by syuchan1005** [comment]
Thanks for your help.
This bug will be fixed in v2.1.5.

Please take it to release.
