### ISSUE TITLE
Cant see selected item

### ISSUE THREAD

**Issue by lloricode** [syuchan1005/GitPrefix#25]
PHPstorm: 2020.1.1
GitPrefix :   2.1.4

In screen shot in image below has already selected item, but din not see,
then sometimes accidental commit without knowing that there already selected item

![Screenshot from 2020-05-13 07-49-23](https://user-images.githubusercontent.com/8251344/81756487-76886900-94ee-11ea-9b4c-3c8bfbbabb57.png)

**Comment by syuchan1005** [comment]
I have contacted Jetbrains about the bug.
(https://youtrack.jetbrains.com/issue/IDEA-239673)
It may take some time.

**Comment by lloricode** [comment]
> I have contacted Jetbrains about the bug.
> (https://youtrack.jetbrains.com/issue/IDEA-239673)
> It may take some time.

thank you

**Comment by syuchan1005** [comment]
Duplicate #24
