### ISSUE TITLE
.emojircを作成してもNo Emojiしか表示されない

### ISSUE THREAD

**Issue by TatsuyaMiyado** [syuchan1005/GitPrefix#4]
IntelliJ IDEA 2017.3 にて、.emojircを作成しても選択肢に `No Emoji` しか表示されない問題が発生しています。

以下は自分が作成した.emojircです。

```
:see_no_evil: バグ修正
:+1: 機能改善
:sparkles: 部分的な機能追加
:tada: 大きな機能追加
:recycle: リファクタリング
:shower: 不要な機能・使われなくなった機能の削除
:green_heart: テストやCIの修正・改善
:shirt: Lintエラーの修正やコードスタイルの修正
:rocket: パフォーマンス改善
:up: 依存パッケージなどのアップデート
:lock: 新機能の公開範囲の制限
:cop: セキュリティ関連の改善
```
![image](https://user-images.githubusercontent.com/8241257/34192749-4ece2b5a-e593-11e7-96f4-557cc728bee7.png)

**Comment by syuchan1005** [comment]
Emoji Prefix 1.4.7で.emojircをコピーし実行したところこちらでは再現できませんでした。
IntelliJ IDEA右下, Event LogにException等ありませんでしょうか

![image](https://user-images.githubusercontent.com/8733829/34193744-aaaea86e-e598-11e7-88ca-a735402cf187.png)

**Comment by TatsuyaMiyado** [comment]
EventLogを確認してみましたが、Emoji Prefixに関するエラーはありませんでした。
バージョンは1.4.7です。

![image](https://user-images.githubusercontent.com/8241257/34194308-85b6509a-e59b-11e7-9833-c1f9464fe962.png)

私の環境はOSがmacOSなんですが、これは関係ありますでしょうか…？
javaなのであまり関係ないでしょうか…

**Comment by syuchan1005** [comment]
手元のMacで試したところ表示されますね
プラグインの再インストールなど試していただけませんか？

**Comment by TatsuyaMiyado** [comment]
![image](https://user-images.githubusercontent.com/8241257/34197808-6c10ecd0-e5ab-11e7-8dfa-22eacee1fd0a.png)

pluginの再インストールを試してみましたが、やはり直らずでした 😓

**Comment by TatsuyaMiyado** [comment]
改行コード、文字コードって関係あるでしょうか？

文字コードは`UTF-8`、改行コードは`CRLF` `LF`を試してみました。

**Comment by syuchan1005** [comment]
Settingを開いて「Editor -> File Types」の中に「Text」があるので「.emojirc」を削除してみてもらえますか？

**Comment by TatsuyaMiyado** [comment]
![image](https://user-images.githubusercontent.com/8241257/34198968-74207c02-e5af-11e7-8f84-220bb1860496.png)

すみません…「Text」が見当たりませんでした
見ている場所が間違っているかもしれません

Preferences -> 左ペインの「Editor」 -> 左ペインの「Code Style」-> 左ペインの「Text」

でしたでしょうか？
検索まどから探しても左ペインには「Text」が出てきませんでした

**Comment by syuchan1005** [comment]
Editor -> File Types -> Text
でした

申し訳ないです

**Comment by TatsuyaMiyado** [comment]
Textから `.emojirc` を削除してみたところ、表示されるようになりました！
すみません、お手数をおかけしました 🙇 

![image](https://user-images.githubusercontent.com/8241257/34199595-a0cd14d4-e5b1-11e7-916e-01384cffcd53.png)

**Comment by syuchan1005** [comment]
動いてよかったです！

次バージョンからファイルタイプの変更をユーザーに確認するようにしたいと思います

**Comment by TatsuyaMiyado** [comment]
はい、よろしくお願いします！

解決しましたのでクローズいたします 🙇
