### ISSUE TITLE
I am a litter confused about how to use it^

### ISSUE THREAD

**Issue by tianwei1992** [syuchan1005/GitPrefix#5]
I'd like to install your EmojiPrefix ,expecting to solve the problem that the emojis  is unrecognized  in my pycharm IDES,but maybe something is wrong with the  jar file named 'EmojiPrefix.jar',,which is downloaded here,https://plugins.jetbrains.com/plugin/9725-emoji-prefix.

![image](https://user-images.githubusercontent.com/32447647/34359124-32fabedc-ea90-11e7-9833-02d9e1582dd1.png)

I have alread done a test with execute' java HelloWord' and  so I'm sure that there is no matter with my java environment.

Now  I am quite wondering what's the matter? Maybe it's not the right way to open your file ?I have read your guid but sincerely I can't understand it.I am sorry I'm not a professional coder and knows little and little……

**Comment by syuchan1005** [comment]
This plugin put emoji in commit message.
1. create file in root(name: .emojirc).
2. write emojis(sample is in README.md)
3. open VCS -> Commit.

Is that what you asked?

**Comment by tianwei1992** [comment]
THanks for reply.Iave sawn that you mentioned  ,but I still don't know ,the jar file and the python file ,which  one should
 I use?Besides,how to open or.create file?with pycharm or java  or something  else ?Thanks  again ~

**Comment by tianwei1992** [comment]
Thanks  for your  reply.I have noticed what you  mentioned ,but I still  don't konw ,which  tool is need  to  create or open a file .pycharm or java ,or something else ?I also noticed  that the  codes  here  in github  are  python files,but what I download from another  link is a jar file .SO I quite doubt which .should I.use ?  finally ,thanks  again !

**Comment by tianwei1992** [comment]
I saw the 3 closed isuues created by others right now,and I noticed that the pictures they provided shows that what  they were using is  IntelliJ IDEA based on Java ,rather than Pycharm.Maybe your readme.txt is provided for IntelliJ IDEA ,too.
Then I want to know how to apply this project to Pycharm?

**Comment by syuchan1005** [comment]
Sorry for my late reply.
All Jetbrains IDE's can use in same way.
It search and install 'Emoji Prefix' inSetting -> Plugins.

**Comment by tianwei1992** [comment]
Oh!That's the point!
I haved installed  the EmojiPrefix as a plugin  on my pycharm platform  right now,and  it does work!
But...emmm……it looks like there;s something incorrect……why does it look like this?Should I do some more settings  ?
![image](https://user-images.githubusercontent.com/32447647/34383275-322a2fb4-eb4f-11e7-8b34-2d6eaa4686be.png)

**Comment by syuchan1005** [comment]
I think that problem reason is character code. It assume UTF-8.

**Comment by tianwei1992** [comment]
Then what kind of character code shoud I change it into?

**Comment by tianwei1992** [comment]
Something confusing is that not all words are shown incorrect,see the following picture:

![image](https://user-images.githubusercontent.com/32447647/34383616-60d9ad2e-eb51-11e7-93f8-b06b70de8ae7.png)


By the way，my origin language  is  Chinese, and  my operating system is windows7
****

**Comment by syuchan1005** [comment]
What is that picture?
I don't understand. What are you trying to do?

**Comment by tianwei1992** [comment]
Oh!It's Chinese!Let me explain: a python programI worte is running on pycharm and the picture you see is the output part.
Detailly ,I am getting top 100 comments of a certain songs from a music website by using requests.post(url).
The problem is that  in these  comments there are some unrecognized  emojis thich can't be shown correctly on pycharm,so I'm trying to fix it.


![image](https://user-images.githubusercontent.com/32447647/34384330-80215862-eb56-11e7-94b5-25067de48b55.png)

**Comment by tianwei1992** [comment]
![image](https://user-images.githubusercontent.com/32447647/34404085-fedbdf20-ebe6-11e7-9c61-ac98a8db531f.png)
Now you see,I have install the plugin correctly,as it is in the picture above.

But during that process,I haven't seen the window named "commit message' like  what is in the following pictures.can you tell me where is it?


![image](https://user-images.githubusercontent.com/32447647/34404021-a74d372c-ebe6-11e7-963d-3391927356dc.png)

**Comment by syuchan1005** [comment]
This plugin can't fix music comments. This plugin attach emoji on Commit Message of Git.
It can't be used for that purpose.

**Comment by tianwei1992** [comment]
Oh……So it is !Thanks for your kind replies and I think I get the answer finally.Ignore my poor English,please!


Since I'm curious about everything,I tried commit with your plugin tight now.And I get it !

What I have done are:

![image](https://user-images.githubusercontent.com/32447647/34405304-957ab18a-ebed-11e7-9af8-22b6527f18c0.png)

Then click 'vcs'-'commit':
![image](https://user-images.githubusercontent.com/32447647/34405319-aecdf430-ebed-11e7-936e-588581481997.png)

Right?

**Comment by syuchan1005** [comment]
Yes. that's right.

**Comment by tianwei1992** [comment]
haha,now it's time to close the issue~
